name: airl

#enable nvidia cuda processing
cuda_en: 1

# every n steps 2560 because rollout 2560 (so, 2560*50)
save_every_nstep : 128000

#buffer experience class
buffer_exp: 
  _target_: library.Imitation.buffer.Buffer

#random seed number
seed: 1

#discount factor (gamma)
gamma: 0.995

#Optimizer for discriminator
disc_optimizer:
  _target_: torch.optim.adam.Adam
  lr: 3.0e-4

#update period for discriminator 
epoch_disc: 5

#batch size
batch_size: 256

units_disc_r:
- [100, 100]

units_disc_v:
- [100, 100]





