name: airl

#enable nvidia cuda processing
cuda_en: 1

# every n steps 2560 because rollout 2560 (so, 2560*50)
save_every_nstep : 128000

#buffer experience class
buffer_exp: 
#  _target_: library.Imitation.buffer.Buffer
  _target_: library.Imitation.buffer.ModifiedBuffer

#random seed number
seed: 15

#discount factor (gamma)
gamma: 0.995

#Optimizer for discriminator
disc_optimizer:
  _target_: torch.optim.adam.Adam
  lr: 3.0e-4

#Optimizer for goal network
goal_net_optimizer:
  _target_: torch.optim.adam.Adam
  lr: 1e-03

#update period for discriminator 
epoch_disc: 6

#batch size
batch_size: 256

units_disc_r:
- [128, 128]

units_disc_v:
- [128, 128]

units_disc_g:
- [128, 128]





